// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDGUWhe5oKf8xzLy7qbhlVxeDv_jsSEdIs",
      authDomain: "cambio-veraz.firebaseapp.com",
      projectId: "cambio-veraz",
      storageBucket: "cambio-veraz.appspot.com",
      messagingSenderId: "145596211075",
      appId: "1:145596211075:web:70db1a5284a261083460b6",
      measurementId: "G-S7PM71NKMT");

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyDGUWhe5oKf8xzLy7qbhlVxeDv_jsSEdIs",
      authDomain: "cambio-veraz.firebaseapp.com",
      projectId: "cambio-veraz",
      storageBucket: "cambio-veraz.appspot.com",
      messagingSenderId: "145596211075",
      appId: "1:145596211075:web:70db1a5284a261083460b6",
      measurementId: "G-S7PM71NKMT");

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: "AIzaSyDGUWhe5oKf8xzLy7qbhlVxeDv_jsSEdIs",
      authDomain: "cambio-veraz.firebaseapp.com",
      projectId: "cambio-veraz",
      storageBucket: "cambio-veraz.appspot.com",
      messagingSenderId: "145596211075",
      appId: "1:145596211075:web:70db1a5284a261083460b6",
      measurementId: "G-S7PM71NKMT");
}
