// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbJKYiehdLK-TzaM9D1v9W8Jv33kB2E3E',
    appId: '1:1315016471:web:0ee44f26d910c4ae897152',
    messagingSenderId: '1315016471',
    projectId: 'cambioveraz-f9229',
    authDomain: 'cambioveraz-f9229.firebaseapp.com',
    storageBucket: 'cambioveraz-f9229.appspot.com',
    measurementId: 'G-Z9XENPJE57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrzuPeos5AUI1W0caHAI1Vdfuo9164DGs',
    appId: '1:1315016471:android:43ceee6d50963ff5897152',
    messagingSenderId: '1315016471',
    projectId: 'cambioveraz-f9229',
    storageBucket: 'cambioveraz-f9229.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4XYFRizvV2_clTIx8SG76rA1HaTeL1_s',
    appId: '1:1315016471:ios:57ae40487f4217f1897152',
    messagingSenderId: '1315016471',
    projectId: 'cambioveraz-f9229',
    storageBucket: 'cambioveraz-f9229.appspot.com',
    iosClientId: '1315016471-8g15if0setfmv3aajk0e8v6nae7f54eh.apps.googleusercontent.com',
    iosBundleId: 'com.example.cambioVeraz',
  );
}
